config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users,
  			 :path => '',
  			 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  			 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  			 				  :registrations => 'registrations'
  			 				 }

  resources :users, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
	belongs_to :recepient, foreign_key: :recepient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recepient_id

	scope :involving, -> (user) do 
		where ('conversations.sender_id = ? OR conversations.recepient_id = ?', user.id, user.id)

		
	end

	scope :between, -> (sender_id, recepient_id) do
		where ('(conversations.sender_id = ? AND conversations.recepient_id = ?) OR (conversations.sender_id = ? AND conversations.recepient_id = ?)', 
			sender_id, recepient_id, recepient_id, sender_id)
	end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationsController
	before_action :authenticate_user!

	def index
		@users = User.all
		@conversations = Conversation.involving(current_user)
	end

	def create
		if Conversation.between(params[:sender_id], params[:recepient_id]).present?
			@conversation = Conversation.between(params[:sender_id], params[:recepient_id]).first
		else
			@conversation = Conversation.create(conversation_params)
		end

		redirect_to conversation_messages_path(@conversation)
	end

	private

		def conversation_params
			params.permit(:sender_id, :recipient_id)
		end
		

end

app/views/conversations/index.html.erb
<div class='row'>
	<div class='col-md-12'>
		<div class='panel panel-default'>
			<div class='panel-heading'>Your chats</div>
			<div class='panel-body'>
				<div class='container'>
					<% @conversations.each do |conversation| %>
						<% other = conversation.sender == current_user ? conversation.recipient : conversation.sender %>
						<%= link_to conversation_messages_path(conversation) do %>
							<div class='row conversation'>
								<div class='col-md-2'>
									<%= image_tag avatar_url(other), class: 'image-circle avatar-medium' %>
								</div>
								<div class='col-md-2'>
									<%= other.fullname %>
									<%= conversation.messages.last.message_time %>
								</div>
								<div class='col-md-8'>
									<%= conversation.messages.last.content %>
								</div>
							</div>
				</div>
			</div>
		</div>

		<h3>All Users</h3>
		<% @users.each do |user| %>
			<% if user != current_user %>
				<%user.fullname %>
				<%= link_to 'Send Message', conversations_path(sender_id: current_user.id, recipient_id: user.id),
				method: 'post' %>
		<% end %>
	</div>
</div>